# Generated by Django 4.2.7 on 2025-07-18 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_reporte', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('grafico', 'Gráfico')], default='pdf', max_length=20)),
                ('filtros_aplicados', models.JSONField(blank=True, default=dict)),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='reportes_generados/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivos_incluidos', models.ManyToManyField(blank=True, related_name='reportes_relacionados', to='archivos.archivoexcel')),
                ('usuario_generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'db_table': 'reportes_generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_grafico', models.CharField(choices=[('bar', 'Barras'), ('line', 'Líneas'), ('pie', 'Circular'), ('scatter', 'Dispersión')], default='bar', max_length=20)),
                ('configuracion', models.JSONField(default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_graficos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Gráfico',
                'verbose_name_plural': 'Configuraciones de Gráficos',
                'db_table': 'configuraciones_graficos',
                'ordering': ['-fecha_creacion'],
                'permissions': [('puede_generar_reportes', 'Puede generar reportes'), ('puede_exportar_datos', 'Puede exportar datos')],
            },
        ),
    ]
