# Generated by Django 4.2.7 on 2025-07-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportegenerado',
            name='datos',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
