# Generated by Django 4.2.7 on 2025-07-18 00:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='archivos_excel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('total_filas', models.IntegerField(default=0)),
                ('total_columnas', models.IntegerField(default=0)),
                ('columnas_disponibles', models.JSONField(blank=True, default=list)),
                ('procesado', models.BooleanField(default=False)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('dependencia', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario_subida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Excel',
                'verbose_name_plural': 'Archivos Excel',
                'db_table': 'archivos_excel',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fila', models.IntegerField()),
                ('datos', models.JSONField()),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('dependencia', models.CharField(blank=True, max_length=200, null=True)),
                ('indicador', models.CharField(blank=True, max_length=300, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='archivos.archivoexcel')),
            ],
            options={
                'verbose_name': 'Registro de Dato',
                'verbose_name_plural': 'Registros de Datos',
                'db_table': 'registros_datos',
                'ordering': ['archivo', 'numero_fila'],
                'indexes': [models.Index(fields=['archivo', 'numero_fila'], name='registros_d_archivo_672650_idx'), models.Index(fields=['anio'], name='registros_d_anio_907115_idx'), models.Index(fields=['dependencia'], name='registros_d_depende_dc6f07_idx'), models.Index(fields=['indicador'], name='registros_d_indicad_251b7f_idx')],
            },
        ),
    ]
