services:
  - type: web
    name: alcaldia-backend
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: db-alcaldia
          property: connectionString

databases:
  - name: db-alcaldia
    databaseName: alcaldia_cordoba
    plan: starter
